services:
  openhab:
    container_name: openhab
    build: ./build/openhab
    image: openhab
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # P1 Smart Meter (Fluvius)
    networks:
      automation:
        ipv4_address: 192.168.5.134
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/hosts:/etc/hosts:ro
      - ./config/openhab/conf:/openhab/conf
      - ./config/openhab/userdata:/openhab/userdata
      - ./config/openhab/addons:/openhab/addons
    environment:
      - TZ=${TZ}
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}

  zwave-js:
    image: zwavejs/zwave-js-ui:latest
    container_name: zwave-js
    restart: unless-stopped
    networks:
      automation:
        ipv4_address: 192.168.5.135    
    environment:
      - TZ=${TZ}
      # Uncomment the following line to expose the WebSocket server to Home Assistant, etc.
      # - ZWAVEJS_EXTERNAL_CONFIG=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/zwavejs/store:/usr/src/app/store
    #ports:
    #  - "8091:8091"    # Web UI
    #  - "3000:3000"    # Z-Wave JS websocket server
    devices:      
      - /dev/ttyAMA0:/dev/ttyAMA0 # Razberry (Z-Wave.me)  

  mqtt:
    container_name: mqtt
    build: ./build/mqtt
    restart: unless-stopped
    networks:
      automation:
        ipv4_address: 192.168.5.129
    environment:
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/mqtt:/mosquitto/config
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
  
  #z-way:
  #  container_name: z-way
  #  build: ./build/z-way
  #  restart: unless-stopped
  #  devices:
  #    - /dev/ttyAMA0:/dev/ttyAMA0 # z-wave (Razberry)
  #  networks:
  #    automation:
  #      ipv4_address: 192.168.5.135
  #  environment:
  #    - TZ=${TZ}
  #  volumes:
  #    - /etc/localtime:/etc/localtime:ro
  #    - /etc/timezone:/etc/timezone:ro
  #    - ./config/z-way:/opt/z-way-server
  #    - z-way-log:/var/log/z-way-server
  #    - ./build/z-way/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf

  node-red:
    container_name: node-red
    build: ./build/node-red
    restart: unless-stopped
    networks:
      automation:
        ipv4_address: 192.168.5.131
    environment:
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/nodered:/data

  velserver:
    container_name: velserver
    build: ./build/velserver
    restart: unless-stopped
    networks:
      automation:
        ipv4_address: 192.168.5.130
    environment:
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0 # Velbus RSUSB Module
    command: /opt/velbus/velserv -v -v -v -v -v
    

  #modbus-tcp-proxy:
  #  container_name: modbus-tcp-proxy
  #  build: ./build/modbus-tcp-proxy
  #  restart: unless-stopped
  #  networks:
  #    automation:
  #      ipv4_address: 192.168.5.158
  #  environment:
  #    - TZ=${TZ}
  #  volumes:
  #    - /etc/localtime:/etc/localtime:ro
  #    - /etc/timezone:/etc/timezone:ro
  #    - ./config/modbus-tcp-proxy/config.yml:/config/modbus-proxy.yml


  #telegraf:
  #  container_name: telegraf
  #  image: telegraf:1.22.3
  #  restart: unless-stopped
  #  user: 1000:995
  #  networks:
  #    automation:
  #      ipv4_address: 192.168.5.x
  #  environment:
  #    TZ: ${TZ} 
  #  volumes:
  #    - /etc/localtime:/etc/localtime:ro
  #    - /etc/timezone:/etc/timezone:ro
  #    - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #    - /var/run/docker.sock:/var/run/docker.sock

  #python:
  #  container_name: python
  #  build: ./build/python
  #  restart: "no"
  #  networks:
  #    automation:
  #  volumes:
  #    - ./build/python/scripts:/usr/src/app


networks:
  automation:
    external: true

volumes:
  mqtt-data:
    name: mqtt-data
  mqtt-log:
    name: mqtt-log

  z-way-log:
    name: z-way-log

  influxdb-data:
    name: influxdb-data